# default config https://github.com/causes/scss-lint/blob/master/config/default.yml

linters:
  BorderZero:
    enabled: false

  Comment:
    enabled: false

  HexNotation:
    enabled: false

  # ignored due to specifity override or missing classes (e.g. homebox)
  IdSelector:
    enabled: true
    exclude:
      - 'sass/base/_forms.scss'
      - 'sass/components/_admin-menu.scss'
      - 'sass/components/_homebox.scss'
      - 'sass/components/_tabs.scss'
      - 'sass/components/layouts/_site-template.scss'

  Indentation:
    severity: warning
    width: 2

  NestingDepth:
    enabled: true
    max_depth: 5

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: true
    allow_element_with_id: false
    exclude:
      - 'sass/base/_forms.scss'

  SelectorDepth:
    enabled: true
    max_depth: 3
    exclude:
      - 'sass/components/form/_dialog-links.scss'
      - 'sass/components/form/_field-collections.scss'

  # added due to drupal classname rendering e.g. class="field_label"
  SelectorFormat:
    convention: '[a-z0-9\-\_]+'

  SingleLinePerProperty:
    allow_single_line_rule_sets: false
